# Generated by Django 5.2.1 on 2026-03-30 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название (для кнопки)')),
                ('image', models.ImageField(upload_to='default_images/', verbose_name='Картинка')),
                ('file_id', models.CharField(blank=True, help_text='Заполнится автоматически при первой отправке ботом', max_length=255, null=True, verbose_name='File ID (Телеграм)')),
            ],
            options={
                'verbose_name': 'Дефолтная картинка',
                'verbose_name_plural': 'Раздел: Картинки',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст с форматированием')),
                ('status', models.CharField(choices=[('draft', '📝 Черновик'), ('scheduled', '⏳ Запланирован'), ('published', '✅ Опубликован'), ('error', '❌ Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('publish_method', models.CharField(choices=[('instant', 'Мгновенно'), ('scheduled', 'По расписанию'), ('slot', 'По слоту')], default='instant', max_length=20, verbose_name='Способ публикации')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время публикации')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Публикация (Пост)',
                'verbose_name_plural': 'Очередь постов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID чата')),
                ('internal_name', models.CharField(max_length=150, verbose_name='Внутреннее название')),
                ('tme_link', models.URLField(blank=True, null=True, verbose_name='Ссылка (t.me)')),
                ('chat_type', models.CharField(choices=[('group', 'Обычная группа'), ('topic_group', 'Группа с топиками'), ('channel', 'Канал')], default='channel', max_length=20, verbose_name='Тип')),
                ('connection_status', models.CharField(choices=[('active', '✅ Активна'), ('no_bot', '⚠️ Бот не добавлен'), ('no_rights', '⚠️ Недостаточно прав'), ('error', '❌ Ошибка')], default='no_bot', max_length=20, verbose_name='Статус подключения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность (вкл/выкл)')),
            ],
            options={
                'verbose_name': 'Группа / Канал',
                'verbose_name_plural': 'Группы и Каналы',
            },
        ),
        migrations.CreateModel(
            name='PublicationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ')], max_length=20, verbose_name='Тип медиа')),
                ('file_id', models.CharField(max_length=255, verbose_name='File ID (Телеграм)')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='panel.publication', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы публикации',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='panel.telegramchat', verbose_name='Группа/Канал'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.IntegerField(verbose_name='ID топика (thread_id)')),
                ('name', models.CharField(max_length=150, verbose_name='Название топика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='panel.telegramchat', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Топик',
                'verbose_name_plural': 'Топики',
                'unique_together': {('chat', 'thread_id')},
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('time', models.TimeField(verbose_name='Время публикации (ЧЧ:ММ)')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='panel.telegramchat', verbose_name='Группа/Канал')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='panel.topic', verbose_name='Топик')),
            ],
            options={
                'verbose_name': 'Слот публикации',
                'verbose_name_plural': 'Слоты публикаций (Неделя)',
                'ordering': ['day_of_week', 'time'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.topic', verbose_name='Топик'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='TG ID')),
                ('fio', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='Юзернейм')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('signature_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отображаемое имя для подписи постов')),
                ('role', models.CharField(choices=[('admin', 'Суперадмин'), ('author', 'Автор публикаций'), ('viewer', 'Наблюдатель')], default='author', max_length=10, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('allowed_chats', models.ManyToManyField(blank=True, to='panel.telegramchat', verbose_name='Доступные группы/каналы')),
            ],
            options={
                'verbose_name': 'Пользователь системы',
                'verbose_name_plural': 'Авторы и Администраторы',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='panel.user', verbose_name='Автор'),
        ),
    ]
