# Generated by Django 5.2.1 on 2026-04-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Аналитика и Статистика',
                'verbose_name_plural': '📊 Аналитика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('panel.publication',),
        ),
        migrations.AddField(
            model_name='publicationmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publications_media/', verbose_name='Файл (из админки)'),
        ),
        migrations.AlterField(
            model_name='publicationmedia',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File ID (Телеграм)'),
        ),
    ]
