# Generated by Django 5.2.1 on 2026-03-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Аналитика и Статистика',
                'verbose_name_plural': '📊 Аналитика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('panel.publication',),
        ),
    ]
